# conda env create -f conda.yml
name: fake-news-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pandas
  - scikit-learn
  - numpy
  - matplotlib
  - plotly
  - lightgbm
  - pip:
    - -r requirements.txt
