# run: conda env create --file environment.yml
name: fake-news-env
channels:
  - defaults
dependencies:
  - python=3.10 # pin version for conda
  - numpy=1.26.4
  - pandas=2.2.1
  - scikit-learn=1.4.2
  - matplotlib=3.8.4
  - seaborn=0.12.2
  - pip=24.0
  -pip:
    # works for regular pip package
    - mlflow==2.13.0
    - openpyxl==3.1.2
